### ISSUE TITLE
Workflow modifications

### ISSUE THREAD

**Issue by skleinfeldt** [isawnyu/isaw.web#21]
Please make workflow changes per the March 4-5 email thread "next question: tutorial on roles, permissions, and sharing".

**Comment by alecpm** [comment]
I've implemented the workflow changes and applied them to the server.  I also initiated the update workflow security mappings method to update permissions for existing content on the site.  However, that process has now been running for 24 hours.  Hopefully it will complete soon without triggering a conflict error (though that's unlikely given the long running time).

**Comment by paregorios** [comment]
I have the impression that this is all good to go. Any objections @alecpm if I close this ticket?

**Comment by skleinfeldt** [comment]
@paregorios It's fine to close it, in fact it's a great idea - if any problems remain, better to open more specific tickets.
