### ISSUE TITLE
Lost ability to add links

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#336]
When trying to add a link, there is no longer a Submit or Ok button in the dialog box.

**Comment by paregorios** [comment]
@k2soule I can't reproduce this error. Here's what I tried:

1. Edit a page.
2. Click and drag to select text in the "Body Text" field.
3. Select the "Insert/Edit Link" button on the editor toolbar.
4. On the "Internal" tab, select the radio button next to the item name to which I wish to link.
5. The "Link Browser" pane appears on the right-hand side of the dialog box, including (at bottom) the "OK" button.
6. Select the "OK" button.
7. Savor my link.

A similar process works with the "External" tab. I note in both cases that the "Link Browser" pane and its "OK" button are not shown until the target information is selected or entered. 

I'm using Firefox. It's possible that Chrome is behaving differently?

**Comment by k2soule** [comment]
I've used both Chrome and Firefox, and in my tests I was trying to insert an external link, specifically.

Now that you've mentioned internal links, I tried that - and it worked. 
*and then* it got interesting:
I went to insert another external link; it gave me no OK button - as before - but I tried switching back to the Internal tab, selecting something (at which point the OK button appears), and then switching back to the External tab; and the newly-appeared OK button remained! Curious indeed.

This is a strange hokey-pokey to have to use every time someone wants to insert an external link, but on the bright side it is a workaround.

**Comment by paregorios** [comment]
I can confirm that the following steps can be used to reproduce the error:

1. Edit a page.
2. Click and drag to select text in the "Body Text" field.
3. Select the "Insert/Edit Link" button on the editor toolbar.
4. Immediately select the "External" tab.
5. On the "External" tab, enter a URL in the first text box.
6. Wonder what to do next ...

**Comment by cguardia** [comment]
I committed a fix to master and updated production manually. Should be fixed now.

**Comment by paregorios** [comment]
On production I'm still not getting a button:

![screen shot 2018-09-19 at 4 15 02 pm](https://user-images.githubusercontent.com/263285/45782001-3db7c400-bc27-11e8-94b6-361afa90e29f.png)

**Comment by cguardia** [comment]
Did you try shift-reload? Not sure how caching is setup on the site, but I see the button.

**Comment by paregorios** [comment]
I have tried the following tests. None of them cause the "OK" button to appear:

 - Firefox Quantum 62.0
   - Disable all tracking protection, add blockers, etc.
   - Shift-reload
   - Delete all history, cookies, and cache and restart

 - Google Chrome 69.0.3497.100 (Official Build) (64-bit)
   - Disable all tracking protection, add blockers, etc.
   - Shift-reload
   - Delete all history, cookies, and cache and restart

 - Safari 11.1.2 (11605.3.8.1)
   - Disable all tracking protection, add blockers, etc.
   - Shift-reload
   - Delete all history, cookies, and cache and restart

I'm running OSX El Capitan 10.11.6 (15G22010)

**Comment by jessesnyder** [comment]
I can confirm that it works for me on production using Chrome. 
![screen shot 2018-09-20 at 10 36 05 am](https://user-images.githubusercontent.com/63560/45836224-14e40d00-bcc1-11e8-892e-9eca21cc8deb.png)

**Comment by paregorios** [comment]
@k2soule can you give it a go and see if it works for you on production or not?

**Comment by paregorios** [comment]
@jessesnyder when you guys test this, how are you authenticating to the plone? Are you going in the standard way or through another port? Is it possible that you're bypassing varnish somehow? or is it possible that this fix is only running on some of our instances and we're playing load-balancer roulette?

**Comment by jessesnyder** [comment]
@paregorios I'm bypassing NYU SSO, but no port magic:
http://isaw.nyu.edu//portal_skins/plone_login/login_form

**Comment by paregorios** [comment]
So now this has cleared while troubleshooting for me 😫. Let's see what @k2soule experiences.

**Comment by paregorios** [comment]
This now works for @k2soule too. Closing as "wondrously fixed."
